# Generated by Django 2.2.3 on 2019-07-04 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "scan_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("scan_url", models.URLField(max_length=300)),
                ("start_timestamp", models.DateTimeField(auto_now=True)),
                ("end_timestamp", models.DateTimeField(null=True)),
                ("exit_code", models.IntegerField(null=True)),
            ],
        )
    ]
